[package]
name = "servus"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1", features = ["attributes"] }
chrono = { version = "0", features = ["serde"] }
femme = "2"
http-types = "2"
markdown = "1.0.0-alpha.3"
regex = "1"
serde = "1"
serde_yaml = "0"
tera = "1"
tide = "0"
tide-acme = "0"
tide-rustls = "0"
tide-tera = "0"
tl = "0"
toml = "0"
walkdir = "2"
yaml-front-matter = "0"
